(function(){
  'use strict';
  var DATA=window.COURSE_DATA;
  if(!DATA||!Array.isArray(DATA.courses)){document.body.innerHTML='<div class="fatal">课程数据未正确加载，请确认 assets 文件夹与网页放在一起。</div>';return;}
  var courses=DATA.courses,days=['周一','周二','周三','周四','周五','周六','周日'];
  var colors=[['#e7efff','#9db9f4','#27457a'],['#e5f4ee','#91c9b2','#205f4a'],['#fff0d8','#e7bd78','#765019'],['#f0e9fb','#b8a0de','#563f79'],['#ffe8e1','#e8a491','#813d2d']];
  var state={query:'',school:'全部开课单位',type:'全部课程属性',level:'全部培养层次',week:2,selected:[]};
  var $=function(id){return document.getElementById(id)};
  function key(c){return c.id+'-'+c.name}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]})}
  try{state.selected=JSON.parse(localStorage.getItem('course-planner-offline')||'[]')}catch(e){}
  function save(){try{localStorage.setItem('course-planner-offline',JSON.stringify(state.selected))}catch(e){}}
  function selectedCourses(){return courses.filter(function(c){return state.selected.indexOf(key(c))>-1})}
  function meetingConflict(a,b){return a.dayIndex===b.dayIndex&&a.periods.some(function(p){return b.periods.indexOf(p)>-1})&&a.weeks.some(function(w){return b.weeks.indexOf(w)>-1})}
  function courseConflict(a,b){return a.meetings.some(function(x){return b.meetings.some(function(y){return meetingConflict(x,y)})})}
  function conflicts(){var s=selectedCourses(),set={};for(var i=0;i<s.length;i++)for(var j=i+1;j<s.length;j++)if(courseConflict(s[i],s[j])){set[key(s[i])]=1;set[key(s[j])]=1}return set}
  function summary(m){var a=Math.min.apply(null,m.periods),b=Math.max.apply(null,m.periods);return m.day+' 第'+a+(a===b?'':'-'+b)+'节 · '+m.weekSpec+' · '+m.room}
  function fillSelect(el,items){el.innerHTML=items.map(function(x){return '<option>'+esc(x)+'</option>'}).join('')}
  var schools=['全部开课单位'].concat(Array.from(new Set(courses.map(function(c){return c.school}))).sort());
  var types=['全部课程属性'].concat(Array.from(new Set(courses.map(function(c){return c.type}))).sort());
  var levels=['全部培养层次'].concat(Array.from(new Set(courses.map(function(c){return c.level}))).sort());
  fillSelect($('schoolFilter'),schools);fillSelect($('typeFilter'),types);fillSelect($('levelFilter'),levels);
  $('weekSelect').innerHTML=Array.from({length:19},function(_,i){return '<option value="'+(i+2)+'">第 '+(i+2)+' 周</option>'}).join('');
  function filtered(){var q=state.query.trim().toLowerCase();return courses.filter(function(c){var hay=[c.name,c.code,c.school,c.discipline,c.type].join(' ').toLowerCase();return(!q||hay.indexOf(q)>-1)&&(state.school==='全部开课单位'||c.school===state.school)&&(state.type==='全部课程属性'||c.type===state.type)&&(state.level==='全部培养层次'||c.level===state.level)})}
  function renderCourses(){var list=filtered(),bad=conflicts();$('resultCount').textContent=list.length+' 门';$('courseList').innerHTML=list.length?list.map(function(c){var k=key(c),on=state.selected.indexOf(k)>-1,clash=!!bad[k];return '<article class="course-card '+(on?'selected ':'')+(clash?'conflict':'')+'"><label class="course-row"><input type="checkbox" data-key="'+esc(k)+'" '+(on?'checked':'')+'><span class="course-copy">'+(clash?'<span class="conflict-tag">冲突</span>':'')+'<strong>'+esc(c.name)+'</strong><small>'+esc(c.code)+' · '+esc(c.credits)+' 学分 · '+esc(c.type)+'</small><small class="time">'+c.meetings.map(summary).map(esc).join('；')+'</small></span></label></article>'}).join(''):'<div class="empty-list">没有找到相符课程</div>';
    Array.from(document.querySelectorAll('[data-key]')).forEach(function(el){el.addEventListener('change',function(){toggle(el.getAttribute('data-key'))})})}
  function toggle(k){var i=state.selected.indexOf(k),c=courses.find(function(x){return key(x)===k});if(i>-1){state.selected.splice(i,1);showNotice('已移除「'+c.name+'」',false)}else{var hits=selectedCourses().filter(function(x){return courseConflict(c,x)});state.selected.push(k);showNotice(hits.length?'注意：「'+c.name+'」与 '+hits.map(function(x){return '「'+x.name+'」'}).join('、')+' 时间冲突':'已加入「'+c.name+'」',hits.length>0)}save();render()}
  function showNotice(text,warn){var n=$('notice');n.hidden=false;n.textContent=text;n.className='notice'+(warn?' warn':'');clearTimeout(showNotice.timer);showNotice.timer=setTimeout(function(){n.hidden=true},5000)}
  function renderStats(){var s=selectedCourses(),bad=conflicts(),n=Object.keys(bad).length;$('selectedCount').textContent=s.length;$('creditCount').textContent=s.reduce(function(a,c){return a+(parseFloat(c.credits)||0)},0).toFixed(1);$('conflictCount').textContent=n?n+' 门':'无';$('conflictStat').className=n?'danger':'safe';$('conflictBanner').hidden=!n}
  function renderTable(){var html='<div class="corner">节次</div>';days.forEach(function(d,i){html+='<div class="day '+(i>4?'weekend':'')+'" style="grid-column:'+(i+2)+'">'+d+'</div>'});for(var p=1;p<=13;p++){html+='<div class="period '+(p===5||p===10?'session':'')+'" style="grid-row:'+(p+1)+'"><b>'+p+'</b><span>'+esc(DATA.meta.periodTimes[String(p)])+'</span></div>';days.forEach(function(_,i){html+='<div class="cell '+(p===5||p===10?'session':'')+'" style="grid-column:'+(i+2)+';grid-row:'+(p+1)+'"></div>'})}
    var s=selectedCourses(),bad=conflicts(),events=[];s.forEach(function(c,ci){c.meetings.forEach(function(m){if(m.weeks.indexOf(state.week)>-1)events.push([c,m,ci])})});events.forEach(function(item){var c=item[0],m=item[1],ci=item[2],a=Math.min.apply(null,m.periods),b=Math.max.apply(null,m.periods),clash=!!bad[key(c)],co=clash?['#fff0ed','#e46e57','#8d2f20']:colors[ci%colors.length];html+='<article class="event '+(clash?'conflict':'')+'" style="grid-column:'+(m.dayIndex+1)+';grid-row:'+(a+1)+' / '+(b+2)+';background:'+co[0]+';border-color:'+co[1]+';color:'+co[2]+'" title="'+esc(c.name+' | '+summary(m))+'"><b>'+esc(c.name)+'</b><span>'+esc(m.room)+'</span><small>'+esc(m.weekSpec)+'</small></article>'});
    if(!s.length)html+='<div class="schedule-empty"><b>课表还是空的</b><span>从左侧勾选课程，它们会按时间落入这里。</span></div>';else if(!events.length)html+='<div class="schedule-empty"><b>第 '+state.week+' 周没有已选课程</b><span>切换周次可查看其他安排。</span></div>';$('timetable').innerHTML=html}
  function render(){renderStats();renderCourses();renderTable()}
  $('searchInput').addEventListener('input',function(e){state.query=e.target.value;renderCourses()});$('schoolFilter').addEventListener('change',function(e){state.school=e.target.value;renderCourses()});$('typeFilter').addEventListener('change',function(e){state.type=e.target.value;renderCourses()});$('levelFilter').addEventListener('change',function(e){state.level=e.target.value;renderCourses()});$('resetFilters').addEventListener('click',function(){state.query='';state.school='全部开课单位';state.type='全部课程属性';state.level='全部培养层次';$('searchInput').value='';$('schoolFilter').value=state.school;$('typeFilter').value=state.type;$('levelFilter').value=state.level;renderCourses()});$('weekSelect').addEventListener('change',function(e){state.week=parseInt(e.target.value,10);renderTable()});$('prevWeek').addEventListener('click',function(){state.week=Math.max(2,state.week-1);$('weekSelect').value=state.week;renderTable()});$('nextWeek').addEventListener('click',function(){state.week=Math.min(20,state.week+1);$('weekSelect').value=state.week;renderTable()});$('clearSelection').addEventListener('click',function(){if(state.selected.length&&confirm('确定清空所有已选课程吗？')){state.selected=[];save();render()}});render();
})();
