(function(){
  'use strict';
  var DATA=window.COURSE_DATA;
  if(!DATA||!Array.isArray(DATA.courses)){document.body.innerHTML='<div class="fatal">课程数据未正确加载，请确认 assets 文件夹与网页放在一起。</div>';return;}
  var courses=DATA.courses,terms=['秋','春'],days=['周一','周二','周三','周四','周五','周六','周日'];
  var colors=[['#e7efff','#9db9f4','#27457a'],['#e5f4ee','#91c9b2','#205f4a'],['#fff0d8','#e7bd78','#765019'],['#f0e9fb','#b8a0de','#563f79'],['#ffe8e1','#e8a491','#813d2d']];
  var state={query:'',school:'全部开课单位',type:'全部课程属性',level:'全部培养层次',semester:'秋',week:2,selected:[]};
  var $=function(id){return document.getElementById(id)};
  function courseKey(c){return c.id+'-'+c.name}function selectionKey(c,t){return t+':'+courseKey(c)}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]})}
  try{state.selected=JSON.parse(localStorage.getItem('course-planner-offline')||'[]').map(function(k){return k.indexOf('秋:')===0||k.indexOf('春:')===0?k:'秋:'+k})}catch(e){}
  function save(){try{localStorage.setItem('course-planner-offline',JSON.stringify(state.selected))}catch(e){}}
  function selectedCourses(term){return courses.filter(function(c){return state.selected.indexOf(selectionKey(c,term))>-1})}
  function allSelected(){return terms.reduce(function(all,t){return all.concat(selectedCourses(t).map(function(c){return{course:c,semester:t}}))},[])}
  function meetingConflict(a,b){return a.dayIndex===b.dayIndex&&a.periods.some(function(p){return b.periods.indexOf(p)>-1})&&a.weeks.some(function(w){return b.weeks.indexOf(w)>-1})}
  function meetingsForTerm(c,t){return c.meetings.filter(function(m){return m.semester===t})}
  function courseConflict(a,b,t){return meetingsForTerm(a,t).some(function(x){return meetingsForTerm(b,t).some(function(y){return meetingConflict(x,y)})})}
  function conflicts(){var set={};terms.forEach(function(t){var s=selectedCourses(t);for(var i=0;i<s.length;i++)for(var j=i+1;j<s.length;j++)if(courseConflict(s[i],s[j],t)){set[selectionKey(s[i],t)]=1;set[selectionKey(s[j],t)]=1}});return set}
  function summary(m){var a=Math.min.apply(null,m.periods),b=Math.max.apply(null,m.periods);return m.day+' 第'+a+(a===b?'':'-'+b)+'节 · '+m.weekSpec+' · '+m.room}
  function exportSummary(m){var a=Math.min.apply(null,m.periods),b=Math.max.apply(null,m.periods);return m.day+' 第'+a+(a===b?'':'-'+b)+'节（'+m.weekSpec+'）'}
  function limitLabel(c){return!c.limit?'暂未公布':c.limit==='0'?'未设限（表中为 0）':c.limit+' 人'}
  function credits(term){return selectedCourses(term).reduce(function(a,c){return a+(parseFloat(c.credits)||0)},0)}
  function fillSelect(el,items){el.innerHTML=items.map(function(x){return'<option>'+esc(x)+'</option>'}).join('')}
  var schools=['全部开课单位'].concat(Array.from(new Set(courses.map(function(c){return c.school}))).sort());
  var types=['全部课程属性'].concat(Array.from(new Set(courses.map(function(c){return c.type}))).sort());
  var levels=['全部培养层次'].concat(Array.from(new Set(courses.map(function(c){return c.level}))).sort());
  fillSelect($('schoolFilter'),schools);fillSelect($('typeFilter'),types);fillSelect($('levelFilter'),levels);
  $('weekSelect').innerHTML=Array.from({length:20},function(_,i){return'<option value="'+(i+1)+'">第 '+(i+1)+' 周</option>'}).join('');$('weekSelect').value=state.week;
  function filtered(){var q=state.query.trim().toLowerCase();return courses.filter(function(c){var hay=[c.name,c.englishName,c.code,c.school,c.discipline,c.type,c.teacher,c.examMethod].join(' ').toLowerCase();return c.semesters.indexOf(state.semester)>-1&&(!q||hay.indexOf(q)>-1)&&(state.school==='全部开课单位'||c.school===state.school)&&(state.type==='全部课程属性'||c.type===state.type)&&(state.level==='全部培养层次'||c.level===state.level)})}
  function renderCourses(){var list=filtered(),bad=conflicts();$('resultCount').textContent=list.length+' 门';$('courseList').innerHTML=list.length?list.map(function(c){var k=selectionKey(c,state.semester),on=state.selected.indexOf(k)>-1,clash=!!bad[k],meetings=meetingsForTerm(c,state.semester),time=meetings.length?meetings.map(summary).map(esc).join('；'):state.semester+'季暂无可参考时间',reference=state.semester==='春'&&meetings.length?'<small class="reference-label">参考 2025–2026 春季课表</small>':'';return'<article class="course-card '+(on?'selected ':'')+(clash?'conflict':'')+'"><label class="course-row"><input type="checkbox" data-key="'+esc(k)+'" '+(on?'checked':'')+'><span class="course-copy">'+(clash?'<span class="conflict-tag">冲突</span>':'')+'<strong>'+esc(c.name)+'</strong><small>'+esc(c.code)+' · '+esc(c.credits)+' 学分 · '+esc(c.type)+'</small><small class="time">'+time+'</small>'+reference+'</span></label></article>'}).join(''):'<div class="empty-list">没有找到相符课程</div>';
    Array.from(document.querySelectorAll('[data-key]')).forEach(function(el){el.addEventListener('change',function(){toggle(el.getAttribute('data-key'))})})}
  function toggle(k){var i=state.selected.indexOf(k),parts=k.split(':'),term=parts.shift(),base=parts.join(':'),c=courses.find(function(x){return courseKey(x)===base});if(!c)return;if(i>-1){state.selected.splice(i,1);showNotice('已移除「'+c.name+'」',false)}else{var hits=meetingsForTerm(c,term).length?selectedCourses(term).filter(function(x){return courseConflict(c,x,term)}):[];state.selected.push(k);showNotice(hits.length?'注意：「'+c.name+'」与 '+hits.map(function(x){return'「'+x.name+'」'}).join('、')+' 时间冲突':'已加入「'+c.name+'」',hits.length>0)}save();render()}
  function showNotice(text,warn){var n=$('notice');n.hidden=false;n.textContent=text;n.className='notice'+(warn?' warn':'');clearTimeout(showNotice.timer);showNotice.timer=setTimeout(function(){n.hidden=true},5000)}
  function renderStats(){var fall=credits('秋'),spring=credits('春'),all=allSelected(),bad=conflicts(),activeBad=selectedCourses(state.semester).filter(function(c){return bad[selectionKey(c,state.semester)]}).length;$('autumnCredit').textContent=fall.toFixed(1)+' / 10';$('springCredit').textContent=spring.toFixed(1)+' / 10';$('totalCredit').textContent=(fall+spring).toFixed(1);$('autumnStat').className=fall>=10?'safe':'progress';$('springStat').className=spring>=10?'safe':'progress';$('manageCount').textContent=all.length;$('conflictBanner').hidden=!activeBad;$('exportMarkdown').disabled=!all.length;terms.forEach(function(t){var button=$('term'+t);button.className=t===state.semester?'active':'';button.querySelector('small').textContent=credits(t).toFixed(1)+' 学分 · '+(credits(t)>=10?'已达最低要求':'还差 '+(10-credits(t)).toFixed(1)+' 分')})}
  function renderSelectedManager(){var all=allSelected(),bad=conflicts();$('drawerSummary').textContent=all.length?'秋季 '+credits('秋').toFixed(1)+' 分，春季 '+credits('春').toFixed(1)+' 分，全学年共 '+(credits('秋')+credits('春')).toFixed(1)+' 分。':'还没有选择课程，可以从左侧课程目录添加。';$('selectedCourseList').innerHTML=all.length?all.map(function(item,i){var c=item.course,t=item.semester,k=selectionKey(c,t),clash=!!bad[k],meetings=meetingsForTerm(c,t),time=meetings.length?meetings.map(exportSummary).map(esc).join('；'):'暂无上一学年对应课程时间',reference=t==='春'&&meetings.length?'<small class="reference-note">参考 2025–2026 春季课表</small>':'';return'<article class="selected-item '+(clash?'conflict':'')+'"><span class="selected-number">'+(i+1)+'</span><div><div class="selected-title"><strong>'+esc(c.name)+'</strong><i class="term-tag">'+t+'季</i>'+(clash?'<i>冲突</i>':'')+'</div><span>'+esc(c.code)+' · '+esc(c.credits)+' 学分 · '+esc(c.type)+'</span><p>'+time+'</p>'+reference+'<small>'+esc(c.teacher||'教师未提供')+' · '+esc(c.examMethod||'考试方式未提供')+'</small></div><button class="remove-course" data-remove-key="'+esc(k)+'" aria-label="删除'+esc(c.name)+'" title="删除'+esc(c.name)+'">删除</button></article>'}).join(''):'<div class="selected-empty"><b>暂无已选课程</b><span>关闭面板后，从课程目录勾选想上的课。</span></div>';Array.from(document.querySelectorAll('[data-remove-key]')).forEach(function(el){el.addEventListener('click',function(){toggle(el.getAttribute('data-remove-key'))})})}
  function exportMarkdown(){var all=allSelected();if(!all.length){showNotice('请先选择课程，再导出 Markdown 文件',true);return}var lines=['# 2026–2027学年我的已选课程','', '> 秋季 '+credits('秋').toFixed(1)+' 学分 · 春季 '+credits('春').toFixed(1)+' 学分 · 全学年合计 '+(credits('秋')+credits('春')).toFixed(1)+' 学分',''];terms.forEach(function(t){lines.push('## '+t+'季学期（'+credits(t).toFixed(1)+' 学分）','');selectedCourses(t).forEach(function(c,i){var meetings=meetingsForTerm(c,t);lines.push('### '+(i+1)+'. '+c.name,'','- 课程代码：'+c.code,'- 课程种类：'+c.type,'- 学分：'+c.credits,'- 上课时间：'+(meetings.length?meetings.map(exportSummary).join('；'):'暂无上一学年对应课程时间'),'- 时间性质：'+(t==='春'&&meetings.length?'参考2025–2026春季课表，并非本学年正式排课':'2026–2027学年正式排课'),'- 限选：'+limitLabel(c),'- 教师：'+(c.teacher||'未提供'),'- 考试方式：'+(c.examMethod||'未提供'),'')})});var url=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/markdown;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='我的双学期选课计划.md';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);showNotice('已导出 '+all.length+' 门课程的双学期计划',false)}
  function renderTable(){var html='<div class="corner">节次</div>';days.forEach(function(d,i){html+='<div class="day '+(i>4?'weekend':'')+'" style="grid-column:'+(i+2)+'">'+d+'</div>'});for(var p=1;p<=13;p++){html+='<div class="period '+(p===5||p===10?'session':'')+'" style="grid-row:'+(p+1)+'"><b>'+p+'</b><span>'+esc(DATA.meta.periodTimes[String(p)])+'</span></div>';days.forEach(function(_,i){html+='<div class="cell '+(p===5||p===10?'session':'')+'" style="grid-column:'+(i+2)+';grid-row:'+(p+1)+'"></div>'})}
    var s=selectedCourses(state.semester),scheduled=s.filter(function(c){return meetingsForTerm(c,state.semester).length}),bad=conflicts(),events=[];s.forEach(function(c,ci){meetingsForTerm(c,state.semester).forEach(function(m){if(m.weeks.indexOf(state.week)>-1)events.push([c,m,ci])})});events.forEach(function(item){var c=item[0],m=item[1],ci=item[2],a=Math.min.apply(null,m.periods),b=Math.max.apply(null,m.periods),clash=!!bad[selectionKey(c,state.semester)],co=clash?['#fff0ed','#e46e57','#8d2f20']:colors[ci%colors.length];html+='<article class="event '+(clash?'conflict ':'')+(m.reference?'reference':'')+'" style="grid-column:'+(m.dayIndex+1)+';grid-row:'+(a+1)+' / '+(b+2)+';background:'+co[0]+';border-color:'+co[1]+';color:'+co[2]+'" title="'+esc(c.name+' | '+summary(m)+(m.reference?' | 参考2025–2026春季课表':''))+'"><b>'+esc(c.name)+'</b><span>'+esc(m.room)+'</span><small>'+(m.reference?'参考上学年 · ':'')+esc(m.weekSpec)+'</small></article>'});
    if(!s.length)html+='<div class="schedule-empty"><b>'+state.semester+'季还没有选课</b><span>从左侧勾选课程，学分会计入本学期。</span></div>';else if(!scheduled.length)html+='<div class="schedule-empty"><b>'+state.semester+'季暂无可参考时间</b><span>上一学年没有找到对应课程，仍可先加入学分规划。</span></div>';else if(!events.length)html+='<div class="schedule-empty"><b>第 '+state.week+' 周没有已选课程</b><span>切换周次可查看其他安排。</span></div>';$('timetable').innerHTML=html}
  function render(){renderStats();renderCourses();renderTable();renderSelectedManager();$('activeTermLabel').textContent=state.semester+'季学期 · 周视图';$('scheduleSource').textContent=state.semester==='春'?'春季时间参考：2025–2026学年课表（非本学年正式排课）':'秋季时间：2026–2027学年正式课表';$('conflictHint').textContent=state.semester==='春'?'红色课程在参考时间上重叠，结果依据上一学年课表。':'红色课程在相同周次、星期和节次上相遇，请调整选择。'}
  function changeTerm(t){state.semester=t;state.week=t==='秋'?2:1;$('weekSelect').value=state.week;$('notice').hidden=true;render()}
  function setDrawer(open){$('selectedDrawer').hidden=!open;document.body.classList.toggle('drawer-open',open);if(open)renderSelectedManager()}
  $('searchInput').addEventListener('input',function(e){state.query=e.target.value;renderCourses()});$('schoolFilter').addEventListener('change',function(e){state.school=e.target.value;renderCourses()});$('typeFilter').addEventListener('change',function(e){state.type=e.target.value;renderCourses()});$('levelFilter').addEventListener('change',function(e){state.level=e.target.value;renderCourses()});$('resetFilters').addEventListener('click',function(){state.query='';state.school='全部开课单位';state.type='全部课程属性';state.level='全部培养层次';$('searchInput').value='';$('schoolFilter').value=state.school;$('typeFilter').value=state.type;$('levelFilter').value=state.level;renderCourses()});$('weekSelect').addEventListener('change',function(e){state.week=parseInt(e.target.value,10);renderTable()});$('prevWeek').addEventListener('click',function(){state.week=Math.max(1,state.week-1);$('weekSelect').value=state.week;renderTable()});$('nextWeek').addEventListener('click',function(){state.week=Math.min(20,state.week+1);$('weekSelect').value=state.week;renderTable()});$('term秋').addEventListener('click',function(){changeTerm('秋')});$('term春').addEventListener('click',function(){changeTerm('春')});$('manageSelected').addEventListener('click',function(){setDrawer(true)});$('closeDrawer').addEventListener('click',function(){setDrawer(false)});$('drawerBackdrop').addEventListener('click',function(){setDrawer(false)});$('exportMarkdown').addEventListener('click',exportMarkdown);document.addEventListener('keydown',function(e){if(e.key==='Escape')setDrawer(false)});$('clearSelection').addEventListener('click',function(){if(state.selected.length&&confirm('确定清空两个学期的所有已选课程吗？')){state.selected=[];save();render()}});render();
})();
